### ISSUE TITLE
Azure networking

### ISSUE THREAD

**Issue by atre** [atre/trn-components#7]
# Description
Ensure we have a full networking setup for AKS cluster

# Tasks:
- [x] Implement remote backend
- [ ] Create VN and set of public and private subnets
- [ ] Implement NAT
- [ ] Create Bastion and firewall
